// This file is auto-generated by @hey-api/openapi-ts

export type ApplicantPublic = {
    user_id: string;
    name: string;
    last_name: string;
    position_title: (string | null);
    position_description: (string | null);
    profile_image: (string | null);
    position_id: string;
};

export type ApplicantsPublic = {
    applicants: Array<ApplicantPublic>;
};

export type ApplyRequest = {
    position_title: string;
    position_description?: (string | null);
};

export type Body_login_login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_profiles_upload_profile_image = {
    file: (Blob | File);
};

export type HTTPExceptionResponse = {
    detail: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MessageCreate = {
    /**
     * Content of the message
     */
    message: string;
};

export type MessagePublic = {
    id: string;
    sender: string;
    sender_name: string;
    sender_last_name: string;
    receiver: string;
    receiver_name: string;
    receiver_last_name: string;
    message: string;
    sender_profile_image: (string | null);
    receiver_profile_image: (string | null);
    sent_at: string;
};

export type ParticipantPublic = {
    user_id: string;
    name: string;
    last_name: string;
    position_title: (string | null);
    position_description: (string | null);
    profile_image: (string | null);
};

export type ParticipantsPublic = {
    participants: Array<ParticipantPublic>;
};

export type PositionCreate = {
    title: string;
    description?: (string | null);
};

export type PositionResponse = {
    positions: Array<PositionSchema>;
};

export type PositionSchema = {
    id: string;
    title: string;
    description?: (string | null);
};

export type PositionUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type ProjectCreate = {
    title: string;
    description?: (string | null);
    project_status?: ProjectStatus;
    tags: Array<TagCreate>;
};

export type ProjectLike = {
    project_id: string;
    is_liked: boolean;
};

export type ProjectPublic = {
    id: string;
    owner_id: string;
    title: string;
    description: (string | null);
    logo: (string | null);
    project_status: ProjectStatus;
    tags: Array<TagSchema>;
};

export type ProjectPublicWithPermissions = {
    id: string;
    owner_id: string;
    title: string;
    description: (string | null);
    logo: (string | null);
    project_status: ProjectStatus;
    tags: Array<TagSchema>;
    permissions?: number;
};

export type ProjectsPublic = {
    projects: Array<ProjectPublic>;
};

export type ProjectStatus = 'Active' | 'Recruitment' | 'Inactive' | 'Private';

export type ProjectUpdate = {
    title?: (string | null);
    description?: (string | null);
    tags?: (Array<TagCreate> | null);
    project_status?: (ProjectStatus | null);
};

export type TagCreate = {
    name: string;
};

export type TagSchema = {
    id: number;
    name: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserLike = {
    user_id: string;
    is_liked: boolean;
};

export type UserPublic = {
    name: string;
    last_name: string;
    email: string;
    is_superuser?: boolean;
    profile_image?: (string | null);
    description?: (string | null);
    status?: UserStatus;
    id: string;
    is_liked?: boolean;
    tags: Array<TagSchema>;
};

export type UserRegister = {
    name: string;
    last_name: string;
    email: string;
    password: string;
};

export type UsersPublic = {
    users: Array<UserPublic>;
};

export type UserStatus = 'Student' | 'PhD student' | 'Graduate' | 'Guest';

export type UserUpdateMe = {
    name?: (string | null);
    last_name?: (string | null);
    description?: (string | null);
    tags?: (Array<TagCreate> | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ApplicantsListApplicantsData = {
    projectId: string;
};

export type ApplicantsListApplicantsResponse = (ApplicantsPublic);

export type LikesGetLikedProjectsData = {
    limit?: number;
    skip?: number;
};

export type LikesGetLikedProjectsResponse = (Array<ProjectPublic>);

export type LikesGetProjectsLikeInfoData = {
    requestBody: Array<(string)>;
};

export type LikesGetProjectsLikeInfoResponse = (Array<ProjectLike>);

export type LikesLikeProjectData = {
    projectId: string;
};

export type LikesLikeProjectResponse = (unknown);

export type LikesUnlikeProjectData = {
    projectId: string;
};

export type LikesUnlikeProjectResponse = (unknown);

export type LikesGetLikedUsersData = {
    limit?: number;
    skip?: number;
};

export type LikesGetLikedUsersResponse = (Array<UserPublic>);

export type LikesGetUsersLikeInfoData = {
    requestBody: Array<(string)>;
};

export type LikesGetUsersLikeInfoResponse = (Array<UserLike>);

export type LikesLikeUserData = {
    userId: string;
};

export type LikesLikeUserResponse = (unknown);

export type LikesUnlikeUserData = {
    userId: string;
};

export type LikesUnlikeUserResponse = (unknown);

export type LoginLoginData = {
    formData: Body_login_login;
};

export type LoginLoginResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRefreshAccessTokenResponse = (Token);

export type LogoutLogoutResponse = ({
    [key: string]: unknown;
});

export type MessagesSendMessageData = {
    receiverId: string;
    requestBody: MessageCreate;
};

export type MessagesSendMessageResponse = (MessagePublic);

export type MessagesGetSentMessagesData = {
    limit?: number;
    skip?: number;
};

export type MessagesGetSentMessagesResponse = (Array<MessagePublic>);

export type MessagesGetReceivedMessagesData = {
    limit?: number;
    skip?: number;
};

export type MessagesGetReceivedMessagesResponse = (Array<MessagePublic>);

export type ParticipantsListParticipantsData = {
    projectId: string;
};

export type ParticipantsListParticipantsResponse = (ParticipantsPublic);

export type ParticipantsUpdateParticipantPositionData = {
    projectId: string;
    requestBody: ApplyRequest;
    userId: string;
};

export type ParticipantsUpdateParticipantPositionResponse = (ParticipantPublic);

export type ParticipantsRemoveParticipantData = {
    projectId: string;
    userId: string;
};

export type ParticipantsRemoveParticipantResponse = (void);

export type PositionsListPositionsData = {
    projectId: string;
};

export type PositionsListPositionsResponse = (PositionResponse);

export type PositionsAddPositionData = {
    projectId: string;
    requestBody: PositionCreate;
};

export type PositionsAddPositionResponse = (PositionSchema);

export type PositionsUpdatePositionData = {
    positionId: string;
    projectId: string;
    requestBody: PositionUpdate;
};

export type PositionsUpdatePositionResponse = (PositionSchema);

export type PositionsDeletePositionData = {
    positionId: string;
    projectId: string;
};

export type PositionsDeletePositionResponse = (void);

export type ProfilesReadMeResponse = (UserPublic);

export type ProfilesReadProfileData = {
    profileId: string;
};

export type ProfilesReadProfileResponse = (UserPublic);

export type ProfilesUpdateProfileData = {
    profileId: string;
    requestBody: UserUpdateMe;
};

export type ProfilesUpdateProfileResponse = (UserPublic);

export type ProfilesReadUserProjectsData = {
    userId: string;
};

export type ProfilesReadUserProjectsResponse = (ProjectsPublic);

export type ProfilesUploadProfileImageData = {
    formData: Body_profiles_upload_profile_image;
    profileId: string;
};

export type ProfilesUploadProfileImageResponse = (UserPublic);

export type ProfilesGetProfileImageData = {
    filename: string;
};

export type ProfilesGetProfileImageResponse = (unknown);

export type ProjectApplicationsApplyToProjectData = {
    positionId: string;
};

export type ProjectApplicationsApplyToProjectResponse = (ApplicantPublic);

export type ProjectApplicationsAcceptApplicationData = {
    positionId: string;
    userId: string;
};

export type ProjectApplicationsAcceptApplicationResponse = (void);

export type ProjectApplicationsRejectApplicationData = {
    positionId: string;
    userId: string;
};

export type ProjectApplicationsRejectApplicationResponse = (void);

export type ProjectsReadProjectData = {
    projectId: string;
};

export type ProjectsReadProjectResponse = (ProjectPublicWithPermissions);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (ProjectPublic);

export type ProjectsDeleteProjectData = {
    projectId: string;
};

export type ProjectsDeleteProjectResponse = (void);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (ProjectPublicWithPermissions);

export type SearchSearchData = {
    limit?: number;
    query: string;
};

export type SearchSearchResponse = (ProjectsPublic);

export type SearchSearchBestProjectsData = {
    limit?: number;
};

export type SearchSearchBestProjectsResponse = (ProjectsPublic);

export type SearchSearchPeopleForProjectData = {
    /**
     * Maximum number of people to return
     */
    limit?: number;
    /**
     * Project ID to find people for
     */
    projectId: string;
};

export type SearchSearchPeopleForProjectResponse = (Array<UserPublic>);

export type SearchGetProjectsData = {
    limit?: number;
    query?: (string | null);
};

export type SearchGetProjectsResponse = (ProjectsPublic);

export type SearchGetPeopleData = {
    limit?: number;
    query?: (string | null);
};

export type SearchGetPeopleResponse = (UsersPublic);

export type SignupSignupUserData = {
    requestBody: UserRegister;
};

export type SignupSignupUserResponse = (UserPublic);

export type UtilsHealthCheckResponse = (boolean);