/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutSearchImport } from './routes/_layout/search'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutDashboardImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutAuthImport } from './routes/_layout/_auth'
import { Route as LayoutProjectProjectIdImport } from './routes/_layout/project/$projectId'
import { Route as LayoutPersonPersonIdImport } from './routes/_layout/person/$personId'
import { Route as LayoutAuthSavedImport } from './routes/_layout/_auth/saved'
import { Route as LayoutAuthMyProjectsImport } from './routes/_layout/_auth/my-projects'
import { Route as LayoutAuthMessagesImport } from './routes/_layout/_auth/messages'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchRoute = LayoutSearchImport.update({
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardRoute = LayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectProjectIdRoute = LayoutProjectProjectIdImport.update({
  path: '/project/$projectId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPersonPersonIdRoute = LayoutPersonPersonIdImport.update({
  path: '/person/$personId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthSavedRoute = LayoutAuthSavedImport.update({
  path: '/saved',
  getParentRoute: () => LayoutAuthRoute,
} as any)

const LayoutAuthMyProjectsRoute = LayoutAuthMyProjectsImport.update({
  path: '/my-projects',
  getParentRoute: () => LayoutAuthRoute,
} as any)

const LayoutAuthMessagesRoute = LayoutAuthMessagesImport.update({
  path: '/messages',
  getParentRoute: () => LayoutAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth': {
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard': {
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search': {
      preLoaderRoute: typeof LayoutSearchImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_auth/messages': {
      preLoaderRoute: typeof LayoutAuthMessagesImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_auth/my-projects': {
      preLoaderRoute: typeof LayoutAuthMyProjectsImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_auth/saved': {
      preLoaderRoute: typeof LayoutAuthSavedImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/person/$personId': {
      preLoaderRoute: typeof LayoutPersonPersonIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/project/$projectId': {
      preLoaderRoute: typeof LayoutProjectProjectIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutAuthRoute.addChildren([
      LayoutAuthMessagesRoute,
      LayoutAuthMyProjectsRoute,
      LayoutAuthSavedRoute,
    ]),
    LayoutAdminRoute,
    LayoutDashboardRoute,
    LayoutItemsRoute,
    LayoutSearchRoute,
    LayoutSettingsRoute,
    LayoutPersonPersonIdRoute,
    LayoutProjectProjectIdRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
